name: CI - Testes Cypress Kanban

on:
  push:
    branches:
      - main
      - Kukac-kanban
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes Cypress
        run: npx cypress run

      - name: Upload dos vídeos dos testes
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload das screenshots dos testes
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
